x_start: 2
y_start: 2
x_goal: 98
y_goal: 98
x_space_size: 100
y_space_size: 100
list_obstacles:
  [
    [[10, -1], [20, -1], [15, 95]],
    [[30, 101], [40, 101], [35, 5]],
    [[50, -1], [60, -1], [55, 95]],
    [[70, 101], [80, 101], [75, 5]],
  ]
