x_start: 2
y_start: 2
x_goal: 98
y_goal: 98
x_space_size: 100
y_space_size: 100
list_obstacles:
  [
    [[5, 5], [6, 5], [8, 6]],
    [[20, -1], [18, 20], [20, 20]],
    [[50, 60], [70, 40], [80, 90], [60, 80]],
  ]
